### ISSUE TITLE
Row Extraction Fails For Scala Case Classes with List Types

### ISSUE THREAD

**Issue by vijay-saikam** [thurstonsand/scala-cass#54]
**Describe the bug**
2 Related Issues With Row Extraction to Scala Case Class when using List type Fields in the latest version of the scala-cass 
`compile ("com.github.thurstonsand:scala-cass_2.12:3.2.1-3.5.0")`

**_Issue 1 :_** If the case class has a field of type _**List[Product]**_, the code doesn't compile. It throws the below error.
_**could not find implicit value for parameter ccd: com.weather.scalacass.CCCassFormatDecoder[MyCaseClass]**_
**_Issue 2 :_** If the case class has a field of type _**List[String]**_, we get the below run-time error
`Exception in thread "main" java.lang.NoSuchMethodError: 'java.util.List   com.datastax.driver.core.Row.getList(java.lang.String, com.google.common.reflect.TypeToken)'
	at com.weather.scalacass.CassFormatDecoder$$anon$5.extract(CassFormatDecoder.scala:128)
	at com.weather.scalacass.CassFormatDecoder$$anon$5.extract(CassFormatDecoder.scala:112)
	at com.weather.scalacass.CassFormatDecoder$$anon$17.extract(CassFormatDecoder.scala:216)
	at com.weather.scalacass.CassFormatDecoder.$anonfun$decode$1(CassFormatDecoder.scala:19)
	at scala.util.Try$.apply(Try.scala:213)
	at com.weather.scalacass.CassFormatDecoder.decode(CassFormatDecoder.scala:18)
	at com.weather.scalacass.CassFormatDecoder.decode$(CassFormatDecoder.scala:17)
	at com.weather.scalacass.CassFormatDecoder$$anon$17.decode(CassFormatDecoder.scala:217)
	at com.weather.scalacass.DerivedCCCassFormatDecoder$$anon$2.decode(CCCassFormatDecoder.scala:17)
	at com.weather.scalacass.DerivedCCCassFormatDecoder$$anon$2.$anonfun$decode$1(CCCassFormatDecoder.scala:18)
	at scala.util.Either$RightProjection.flatMap(Either.scala:701)
	at com.weather.scalacass.DerivedCCCassFormatDecoder$$anon$2.decode(CCCassFormatDecoder.scala:17)
	at com.weather.scalacass.DerivedCCCassFormatDecoder$$anon$2.$anonfun$decode$1(CCCassFormatDecoder.scala:18)
	at scala.util.Either$RightProjection.flatMap(Either.scala:701)
	at com.weather.scalacass.DerivedCCCassFormatDecoder$$anon$2.decode(CCCassFormatDecoder.scala:17)
	at com.weather.scalacass.DerivedCCCassFormatDecoder$$anon$3.decode(CCCassFormatDecoder.scala:24)
	at com.weather.scalacass.CCCassFormatDecoder.as(CCCassFormatDecoder.scala:37)
	at com.weather.scalacass.CCCassFormatDecoder.as$(CCCassFormatDecoder.scala:37)
	at com.weather.scalacass.DerivedCCCassFormatDecoder.as(CCCassFormatDecoder.scala:7)
	at com.weather.scalacass.syntax$RichRow$.as$extension1(syntax.scala:12)`

**To Reproduce**
1. Create a Cassandra Table With two fields of type List[String] and List[Product]. Makes the Lists Frozen
2. Create a scala class to match the table schema. List is the scala List type. Not java.util.List
3. Try to fetch a row and cast to case class using as[T]

**Expected behavior**
List fields of primitive types or product types should also be casted to the corresponding case class correctly

**Code Snippets**

**Additional context**

**Comment by thurstonsand** [comment]
what do you expect to happen if you decode a `Product` type?

I'll look into the `List[String]` error, but to check, what version of jdk are you using?

**Comment by thurstonsand** [comment]
just FYI, looking into it a bit more, you MUST be using jdk 8 (I personally am using AdoptOpenJDK jdk8u265-b01 HotSpot) due to the version of Cassandra supported here

**Comment by vijay-saikam** [comment]
I am Using Open JDK 11 and Scala 2.12  The product is a class **MyClass** that equates the Cassandra schema.
I expect the row to be decoded to **MyClass** which contains a List of **MyOtherClass** as one of the fields

**Comment by thurstonsand** [comment]
sure, I have just removed that line.

So I would try using jdk8 and see how that goes. however, I still would like to know what you expect ScalaCass to do when trying to decode a `Product` type. what behavior do you expect?

**Comment by thurstonsand** [comment]
ok, I saw your comment. Does `MyOtherClass`  contain only [supported types](https://thurstonsand.github.io/scala-cass/cass3/type-mappings.html)?

**Comment by vijay-saikam** [comment]
Ah! I did not check the supported types. It has some fields which are lists of other product types. More like

case class MyClass(someVar: Int, someProductVar: List[MyOtherClass])
case class MyOtherClass(myVar: Int)

So yes most of the field types are in the supported list but additionally they have nested Product types and collection of product types. Is that not supported ?

**Comment by thurstonsand** [comment]
actually, I take that back. What you're saying does not make sense.

using your verbiage, `MyClass` == cassandra table. 

`MyOtherClass` == a column in that table? what is the cassandra type of that case class? It is possible if you just want it to be `Int`. what you would do is:

```scala
case class MyOtherClass(myVar: Int)
object MyOtherClass {
    implicit val cassEncoder: CassFormatEncoder[MyOtherClass] = CassFormatEncoder[Int].map[MyOtherClass](_.myVar)
    implicit val cassDecoder: CassFormatDecoder[MyOtherClass] = CassFormatDecoder[Int].map[MyOtherClass](MyOtherClass.apply)
}
```
and now ScalaCass knows how to encode/decode that int-as-a-case-class.

[more info on custom encoders/decoders here](https://thurstonsand.github.io/scala-cass/cass3/custom-encoders-decoders.html)

**Comment by vijay-saikam** [comment]
Ok Sorry about not being clear. 
Yes `MyClass` == `MyCassandraTable`, And
`MyOtherClass` == `Cassandra UDT` which is a field in the main Table

`Cassadndra UDT` is a two field type, id and value both Strings

A better structure of my types would be

`Case class MyClass(myVar: Int, myOtherVar: List[MyOtherClass])`
`case class MyOtherClass(id: String, value: String)`

I will try adding custom decoder and i'll let you know. In the meantime can you also delete your edit history on the comment i requested you to delete ?

**Comment by thurstonsand** [comment]
deleted history.

I have not added support for UDTs, but it looks like it wouldnt be all that hard. custom decoder won't get you there because I just don't support them right now. if you have the choice, an alternative route would be to just convert to json and store it as a string (where your custom encoder/decoder handles that translation). let me take a look at supporting UDTs tho

**Comment by thurstonsand** [comment]
actually, if you do the encoders/decoders [from scratch](https://thurstonsand.github.io/scala-cass/cass3/custom-encoders-decoders.html#create-a-new-encoderdecoder-from-scratch), you can do the UDT extraction properly. so that is an option for you.

**Comment by vijay-saikam** [comment]
Sure thanks. I was looking in that route. I am fairly new to shapeless and scala generics, so ill try to do it. It will be a learning for me as well.  Can you update when you figure out, what the issue is with list of strings.

**Comment by thurstonsand** [comment]
do you still get the `List[String]` error with jdk8?
